server:
  port: 0

spring:
  application:
    name: catalog-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        generate_ddl: true
        format_sql: true
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/msa
    username: sa
    password: 12
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  sql:
    init:
      mode: always

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.example.java.catalogservice: DEBUG