server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\\Users\\rkdeh\\msa_ecommerce\\config-service
        git:
          uri: file:////C:\\Users\\rkdeh\\msa_ecommerce\\git-local-repo